version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    networks:
      - app-network

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - /${PWD}/views/:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - nodejs
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - /${PWD}/views/:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email rahulsamaranayake@yahoo.com --agree-tos --no-eff-email --force-renewal -d dostoevsky.rest  -d www.dostoevsky.rest

volumes:
  certbot-etc:
  certbot-var:
  # web-root:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     device: ${PWD}/dostoevskyrest/views/
  #     o: bind

networks:
  app-network:
    driver: bridge